apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-14T20:06:34Z"
  generation: 1
  labels:
    app: winejs-db
  name: winejs-db
  namespace: default
  resourceVersion: "11083"
  selfLink: /apis/apps/v1/namespaces/default/deployments/winejs-db
  uid: 15fb0ab5-1e70-4f12-872a-f09e62297713
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: winejs-db
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: winejs-db
    spec:
      containers:
      - image: gcr.io/winejs-db/image:v1.0.6
        imagePullPolicy: IfNotPresent
        name: image
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2020-11-14T20:07:22Z"
    lastUpdateTime: "2020-11-14T20:07:22Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-11-14T20:06:34Z"
    lastUpdateTime: "2020-11-14T20:07:22Z"
    message: ReplicaSet "winejs-db-b7f4bf646" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
